//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Итоговая_ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query9Table
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SalesPrice { get; set; }
        public int IdUnitStorage { get; set; }
    
        public virtual UnitStorages UnitStorages { get; set; }
    }
}
