//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Итоговая_ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        //public int Id { get; set; }
        //public int IdProduct { get; set; }
        //public int Count { get; set; }
        //public int IdSeller { get; set; }
        //public System.DateTime DateSale { get; set; }
    
        //public virtual Products Products { get; set; }
        //public virtual Sellers Sellers { get; set; }
    }
}
