//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Итоговая_ADO.NET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WholesaleStoreEntities : DbContext
    {
        public WholesaleStoreEntities()
            : base("name=WholesaleStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<UnitStorages> UnitStorages { get; set; }
        public virtual DbSet<Query9Table> Query9Table { get; set; }
        public virtual DbSet<ProductsCopy> ProductsCopy { get; set; }
        public virtual DbSet<Query1> Query1 { get; set; }
        public virtual DbSet<Query2> Query2 { get; set; }
        public virtual DbSet<Query3> Query3 { get; set; }
        public virtual DbSet<Query7> Query7 { get; set; }
        public virtual DbSet<Query8> Query8 { get; set; }
    
        public virtual int Query10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Query10");
        }
    
        public virtual int Query11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Query11");
        }
    
        public virtual int Query12()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Query12");
        }
    
        public virtual ObjectResult<Query4_Result> Query4(Nullable<double> commissions)
        {
            var commissionsParameter = commissions.HasValue ?
                new ObjectParameter("commissions", commissions) :
                new ObjectParameter("commissions", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Query4_Result>("Query4", commissionsParameter);
        }
    
        public virtual ObjectResult<Query5_Result> Query5(Nullable<decimal> lowSalesPrice, Nullable<decimal> upSalesPrice)
        {
            var lowSalesPriceParameter = lowSalesPrice.HasValue ?
                new ObjectParameter("lowSalesPrice", lowSalesPrice) :
                new ObjectParameter("lowSalesPrice", typeof(decimal));
    
            var upSalesPriceParameter = upSalesPrice.HasValue ?
                new ObjectParameter("upSalesPrice", upSalesPrice) :
                new ObjectParameter("upSalesPrice", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Query5_Result>("Query5", lowSalesPriceParameter, upSalesPriceParameter);
        }
    
        public virtual ObjectResult<Query6_Result> Query6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Query6_Result>("Query6");
        }
    
        public virtual int Query6Main()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Query6Main");
        }
    
        public virtual int Query9()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Query9");
        }
    }
}
