//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_ASP.NET
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Residents
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [StringLength(10, ErrorMessage = "Длина строки должна быть 10 символов")]
        public string Passport { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        public string Patronymic { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        public int IdCity { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [DataType(DataType.Date)]
        public System.DateTime SettlementDate { get; set; }
        [Required(ErrorMessage = "Поле должно быть установлено")]
        public int IdRoom { get; set; }
        public bool IsEvicted { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
