//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_ASP.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сleaning
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int IdFloor { get; set; }
        public int IdDay { get; set; }
    
        public virtual DaysWeek DaysWeek { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Floors Floors { get; set; }
    }
}
